# Generated by Django 3.2.9 on 2022-09-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
