# Generated by Django 3.2.9 on 2022-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_auto_20220921_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
