# Generated by Django 3.2.9 on 2022-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avartar.jpg', null=True, upload_to=''),
        ),
    ]
